### ISSUE TITLE
Support HTML report generation

### ISSUE THREAD

**Issue by CashWilliams** [flood-io/ruby-jmeter#86]
I've not tried this yet, but looking at jMeter docs page http://jmeter.apache.org/usermanual/generating-dashboard.html it appears you can launch jmeter with `-e -o <Path to output folder>` which will create a default HTML report.

**Comment by CashWilliams** [comment]
I think this would just be a matter of passing the params to https://github.com/flood-io/ruby-jmeter/blob/master/lib/ruby-jmeter/dsl.rb#L559

**Comment by pmouawad** [comment]
@CashWilliams , you're correct.

**Comment by 90kts** [comment]
Generally the best way to do this is to get ruby-jmeter to generate a JMX file for you locally. You can then run your test with whatever configuration you like, specifying -t ruby-jmeter.jmx as the command line option.

I don't think we can cater for all the different command line options / variations users would expect which is why I recommend this approach.
